;;; lsp-c-config.el --- C/C++ LSP configuration -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; C, C++, and Objective-C via clangd (lsp-mode built-in lsp-clangd).
;;
;; Requires clangd on PATH.  On macOS it ships with Xcode Command Line Tools:
;;   xcode-select --install
;; or via Homebrew:
;;   brew install llvm   # then ensure $(brew --prefix llvm)/bin is on PATH
;;
;; clangd reads compile_commands.json from the project root (generated by
;; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON or bear/compiledb for make).

;;; Code:

(use-package lsp-clangd
  :straight nil  ; built into lsp-mode
  :after lsp-mode
  :hook ((c-mode     . lsp-deferred)
         (c++-mode   . lsp-deferred)
         (c-ts-mode  . lsp-deferred)
         (c++-ts-mode . lsp-deferred)
         (objc-mode  . lsp-deferred)))

(provide 'lsp-c-config)

;;; lsp-c-config.el ends here
